version: "3"

services:
  app-web:
    build:
      context: .
      dockerfile: ./Dockerfile.web
    ports:
      - "8086:8080"
    links:
      - app-db

  app-db:
    build:
      context: .
      dockerfile: ./Dockerfile.db
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/init-db/:/docker-entrypoint-initdb.d/

volumes:
  db-data:
    driver: local
